services:
  micropython:
    image: danb0b/micropython
    ports:
    - 5000:5000
    volumes:
      - ./code:/code
    working_dir: /code
    # entrypoint: micropython
    # entrypoint: /bin/bash
    # command: main.py
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: bash -c "micropython boot.py; micropython main.py"
